### ISSUE TITLE
VS Code unable to resolve classes

### ISSUE THREAD

**Issue by jasonwbarnett** [KevinMarquette/Chronometer#27]
When opening this repo in VS Code I get the following error:

![Screen Shot 2020-06-26 at 10 21 30 AM](https://user-images.githubusercontent.com/862300/85867491-f9137200-b796-11ea-98c9-56abcde07b09.png)

Do you get the same error? Any tips for getting VS Code to recognize the classes in this project?

**Comment by KevinMarquette** [comment]
Because the classes are in a different file, VSCode has issues. If you load the classes into your session then I think it handles it better. Run each class file individually and see if it helps.

Also look into PSProfiler, it took my idea here and ran with it. https://twitter.com/IISResetMe/status/1273381595001602055?s=19
